url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "<img src="{{ site.github.url }}/assets/bsis-logo.png"> Minho Jeong" # the name of your site, e.g. ACME Corp.
description: ""

sass:
  sass_dir: _sass
