menu:
- {name: 'CURRICULUM VITAE', url: '/cv'}
- {name: 'ARCHIVE', url: '/archive'}
- {name: 'CONTACT', url: '/contact'}

archive:
- {name: 'Mathematics', url: '/mathematics'}
- {name: 'Lecture Notes', url: '/lecture-notes'}

admission:
- {name: 'College Admissions', url: '/adm'}

data:
- {name: 'PhyPhox (May 2024)', url: '/may-2024-phyphox'}

social:
- {icon: 'envelope', link: 'mailto:mjeong [at] kaist [dot] ac [dot] kr'}
- {icon: 'orcid', link: 'https://orcid.org/0009-0000-6873-5271'}

contacts:
- {name: 'Minho Jeong', title: 'Undergraduate Student', school: 'Korea Advanced Institute of Science and Technology', number: 'Class of 2029', email: 'mjeong [at] kaist [dot] ac [dot] kr', orcid: '0009-0000-6873-5271'}
