menu:
- {name: 'CURRICULUM VITAE', url: '/cv'}
- {name: 'ARCHIVE', url: '/archive'}
- {name: 'CONTACT', url: '/contact'}

archive:
- {name: 'Mathematics', url: '/mathematics'}
- {name: 'Lecture Notes', url: '/lecture-notes'}

data:
- {name: 'PhyPhox Experiment', url: '/may-2024-phyphox'}

social:
- {icon: 'envelope', link: 'mailto:mjeong [at] kaist [dot] ac [dot] kr'}
- {icon: 'orcid', link: 'https://orcid.org/0009-0000-6873-5271'}

contacts:
- {name: 'Minho Jeong', title: 'Student & Amateur Mathematician', school: 'Busan Il Science High School', number: 'Class of 2025 (11th Generation)', email: 'mjeong [at] kaist [dot] ac [dot] kr', orcid: '0009-0000-6873-5271'}
