menu:
- {name: 'CURRICULUM VITAE', url: '/cv'}
- {name: 'ARCHIVE', url: '/archive'}
- {name: 'CONTACT', url: '/contact'}

archive:
- {name: 'Mathematics', url: '/mathematics'}
- {name: 'Lecture Notes', url: '/lecture-notes'}

data:
- {name: 'PhyPhox Experiment', url: '/may-2024-phyphox'}

postech:
- {name: 'POSTECH', url: '/postech'}

social:
- {icon: 'google', link: 'mailto:2430412@bsis.hs.kr'}
- {icon: 'orcid', link: 'https://orcid.org/0009-0000-6873-5271'}

contacts:
- {name: 'Minho Jeong', title: 'Student & Amateur Mathematician', school: 'Busan Il Science High School', number: '11th (Class of 2025)', email: '2430412@bsis.hs.kr', orcid: '0009-0000-6873-5271'}
