menu:
- {name: 'CURRICULUM VITAE', url: '/cv'}
- {name: 'COURSEWORK', url: '/coursework'}
- {name: 'CONTACT', url: '/contact'}

acceptances:
- {name: 'Acceptances', url: '/acceptances'}

social:
- {icon: 'envelope', link: 'mailto:mjeong [at] kaist [dot] ac [dot] kr'}
- {icon: 'orcid', link: 'https://orcid.org/0009-0000-6873-5271'}

contacts:
- {name: 'Minho Jeong', title: 'Undergraduate Student (Freshman)', school: 'Korea Advanced Institute of Science and Technology', number: 'Class of 2029', email: 'mjeong [at] kaist [dot] ac [dot] kr', orcid: '<span>0009</span>-<span>0000</span>-<span>6873</span>-<span>5271</span>'}
