name: Build Jekyll and Push to gh-pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Build Jekyll Site
        run: |
          echo "url: \"http://mathsci.kaist.ac.kr\"" >> _config.yml
          echo "baseurl: \"/~mjeong\"" >> _config.yml
          echo "permalink: pretty" >> _config.yml
          bundle exec jekyll build

          find _site -type f -name "*.html" -exec sed -i 's|https://mino-jeong.github.io|http://mathsci.kaist.ac.kr/~mjeong|g' {} +

          find _site -type f -name "*.html" -exec sed -i 's|href="/|href="/~mjeong/|g' {} +
          find _site -type f -name "*.html" -exec sed -i 's|src="/|src="/~mjeong/|g' {} +
          find _site -type f -name "*.html" -exec sed -i 's|/~mjeong//|//|g' {} +
          find _site -type f -name "*.html" -exec sed -i 's|/~mjeong/~mjeong|/~mjeong|g' {} +

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
